In [5]:
import numpy as np;

In [6]:
scores = np.array([0, 12, 4, 3]);

In [7]:
scores

array([ 0, 12,  4,  3])

In [8]:
python_list = list(range(100));
python_list[:5]

[0, 1, 2, 3, 4]

In [9]:
import sys

In [10]:
sys.getsizeof(python_list[0])*len(python_list)

2800

In [11]:
numpy_array = np.arange(100);
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [12]:
numpy_array.nbytes


800

In [52]:
#dir(np)


In [16]:
rev_q1 = np.array([10, 12, 9])
rev_q1.ndim

1

In [20]:
rev = np.array([[10, 12, 9], [15, 11, 13]])
rev.ndim

2

In [21]:
rev[1, 0]

15

In [22]:
rev[1, 0] = 14

In [23]:
rev.dtype

dtype('int64')

In [24]:
rev = np.array([[10, 12, 9], [15, 11, 13]], dtype=np.float64)
rev.dtype

dtype('float64')

In [25]:
rev.itemsize

8

In [26]:
rev.size

6

In [27]:
rev.shape

(2, 3)

In [29]:
np.sort(rev, axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [30]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
 np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.arange(20, 30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [34]:
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [35]:
# create only 5 elements
np.linspace(12, 20, 5)

array([12., 14., 16., 18., 20.])

In [36]:
rev.ravel()

array([10., 12.,  9., 15., 11., 13.])

In [37]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [39]:
# reshape the array
rev.reshape(3, 2)

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [40]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [41]:
rev.min()

9.0

In [44]:
rev.max()

15.0

In [45]:
rev.sum(axis=1)

array([31., 39.])

In [47]:
rev.sum(axis=0) #vertical axis

array([25., 23., 22.])

In [48]:
for row in rev:
    print("row: ", row)

row:  [10. 12.  9.]
row:  [15. 11. 13.]


In [49]:
b = np.array([1, 4, 16])

In [51]:
#standard deviation
np.std(b)

6.48074069840786

In [55]:
# sales data for quater 1
# rows represent different products, columns represent different regions

q1 = np.array([
    [200, 220, 250],  # product A
    [150, 180, 210],  # product B
    [300, 330, 360]   # product C
]);

q2 = np.array([
    [209, 231, 259], # product A
    [155, 192, 222], # product B
    [310,  340, 375] # product C
])

In [57]:
# total sales
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [58]:
# sales unit growth
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [59]:
# what is the % increase
(q2 - q1)*100 / q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [61]:
prices = np.array([
    [10, 12, 11], # prices for product A in different regions
    [8, 9, 10],   # prices for product B
    [15,16, 17]   # prices for product C
])



In [63]:
q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [67]:
q1_discounts = q1_revenue*0.2
q1_discounts

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [68]:
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [69]:
np.sum(net_revenue)

22568.0

In [70]:
features = np.array([
    [2000, 3],  # houes 1
    [1800, 2] # house 2
])

In [71]:
 weights = np.array([150, 50000])

In [72]:
np.dot(features, weights)

array([450000, 370000])

In [73]:
# customer ID, Name

c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])

# Customer I, Purchase Amount , Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])


In [74]:
# how can you create a combine array that has all c and d data
np.hstack((c, d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [75]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [76]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy']
])

In [77]:
np.vstack((c, e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [78]:
#similary you can see np.hsplit() to split array horizontally
#you can see np.vsplit() to split array verticaly

In [79]:
monthly_sales = np.array([30, 33, 35, 28, 42]);

In [82]:
result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [83]:
monthly_sales[result]

array([30, 28])